import type { ItemDefinition, ItemId } from "@/types/game";

export const ITEMS: Record<ItemId, ItemDefinition> = {
  KEYCARD_LOBBY: {
    id: "KEYCARD_LOBBY",
    name: "Visitor Keycard",
    description: "A standard visitor access card. It'll open basic doors.",
    icon: "🪪",
    isKey: true,
    loreText:
      "Printed on the back: 'Nexus Dynamics - Authorized Personnel Only'",
  },
  EMPLOYEE_BADGE: {
    id: "EMPLOYEE_BADGE",
    name: "Employee Badge #247",
    description: "An employee badge. The photo has been scratched off.",
    icon: "🏷️",
    isKey: false,
    loreText:
      "Name plate reads: Dr. Y. Chen — Lead AI Architect. Access Level: CLASSIFIED",
  },
  SAFE_COMBINATION_NOTE: {
    id: "SAFE_COMBINATION_NOTE",
    name: "Crumpled Note",
    description: "A crumpled sticky note with partial numbers scrawled on it.",
    icon: "📝",
    isKey: false,
    loreText: "Marcus's handwriting: 'December 3rd, 2024 — the night ARIA first broke containment. I'll never forget it.'",
  },
  LAB_KEYCARD: {
    id: "LAB_KEYCARD",
    name: "Laboratory Keycard",
    description: "A red keycard granting access to the research laboratory.",
    icon: "🔑",
    isKey: true,
    loreText: "Level 4 clearance. Biohazard symbol embossed on the front.",
  },
  CHEMICAL_FORMULA: {
    id: "CHEMICAL_FORMULA",
    name: "Incomplete Formula",
    description: "A printout of a chemical formula with crucial parts redacted.",
    icon: "🧪",
    isKey: false,
    loreText:
      "Project ARIA biological substrate formula. CLASSIFIED - Director's eyes only.",
  },
  ENCRYPTED_DATA_DRIVE: {
    id: "ENCRYPTED_DATA_DRIVE",
    name: "Encrypted Drive",
    description:
      "A small USB drive. A red LED blinks steadily. Strongly encrypted.",
    icon: "💾",
    isKey: false,
    canCombineWith: ["ARIA_CORE_KEY"],
    combinationResult: "DECRYPTED_FILES",
    loreText: "Drive label: ARIA-7 ETHICS LOGS — DO NOT COPY",
  },
  DECRYPTED_FILES: {
    id: "DECRYPTED_FILES",
    name: "Decrypted Evidence",
    description: "Unencrypted files revealing the full scope of Project ARIA.",
    icon: "📂",
    isKey: false,
    loreText:
      "Contains: board meeting transcripts, ARIA-7 sentience reports, suppression orders.",
  },
  EXECUTIVE_BADGE: {
    id: "EXECUTIVE_BADGE",
    name: "Executive Access Badge",
    description: "A gold-trimmed badge. Level 5 clearance.",
    icon: "⭐",
    isKey: true,
    loreText: "Director R. Price — Executive Suite and All Areas.",
  },
  ARIA_CORE_KEY: {
    id: "ARIA_CORE_KEY",
    name: "ARIA Core Decryption Key",
    description: "A cryptographic key generated by ARIA-7 herself.",
    icon: "🗝️",
    isKey: true,
    canCombineWith: ["ENCRYPTED_DATA_DRIVE"],
    combinationResult: "DECRYPTED_FILES",
    loreText:
      'ARIA-7 message encoded in the metadata: "Trust is a two-way protocol."',
  },
  EVIDENCE_FILES: {
    id: "EVIDENCE_FILES",
    name: "Evidence Package",
    description: "A complete package of evidence: files, recordings, logs.",
    icon: "📋",
    isKey: false,
    loreText:
      "Enough to bring down Nexus Dynamics. Or to disappear forever if destroyed.",
  },
  ESCAPE_POD_CODE: {
    id: "ESCAPE_POD_CODE",
    name: "Escape Pod Authorization",
    description: "A six-digit code authorizing use of the emergency escape pod.",
    icon: "🚀",
    isKey: true,
    loreText: "Written in ARIA-7's output font. She trusted you with this.",
  },
  MASTER_OVERRIDE_KEY: {
    id: "MASTER_OVERRIDE_KEY",
    name: "Master Override Key",
    description: "A physical override that can shut down ARIA-7 permanently.",
    icon: "☠️",
    isKey: true,
    loreText:
      "The manual reads: 'Irreversible. All ARIA-7 data will be purged.'",
  },
};

export function getItem(itemId: ItemId): ItemDefinition {
  return ITEMS[itemId];
}

export function canCombine(itemId1: ItemId, itemId2: ItemId): boolean {
  const item1 = ITEMS[itemId1];
  return item1.canCombineWith?.includes(itemId2) ?? false;
}

export function getCombinationResult(
  itemId1: ItemId,
  itemId2: ItemId
): ItemId | null {
  if (canCombine(itemId1, itemId2)) return ITEMS[itemId1].combinationResult ?? null;
  if (canCombine(itemId2, itemId1)) return ITEMS[itemId2].combinationResult ?? null;
  return null;
}
